# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_type',
            field=models.CharField(choices=[('create_session', 'дневные отчёты'), ('view_report', 'просмотр отчётов'), ('all', 'полный')], default='all', help_text='Тип доступа к кинотетрам', max_length=16, verbose_name='Доступ'),
            preserve_default=False,
        ),
    ]
