# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170127_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cinema_chain',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cinemas',
        ),
    ]
