# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170131_1047'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='access_to_main_reports',
            field=models.BooleanField(default=False, help_text='Просмотр отчётов по всем кинотеатрам'),
        ),
    ]
