# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170217_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='access_to_main_reports',
            new_name='view_all_report',
        ),
    ]
