# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170217_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='view_all_report',
            new_name='view_all_reports',
        ),
    ]
