# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 09:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('active_from', models.DateField()),
                ('active_to', models.DateField()),
            ],
            options={
                'verbose_name': 'Доп. сошлашение',
                'verbose_name_plural': 'Дополнительные соглашения',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Сеть',
                'verbose_name_plural': 'Сети кинотеатров',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Chain', verbose_name='Сеть')),
            ],
            options={
                'verbose_name': 'Кинотеатр',
                'verbose_name_plural': 'Кинотеатры',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CinemaHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=32)),
                ('seats_count', models.PositiveSmallIntegerField()),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='common.Cinema')),
            ],
            options={
                'verbose_name': 'Кинозал',
                'verbose_name_plural': 'Кинозалы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Городa',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Формат',
                'verbose_name_plural': 'Форматы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=128)),
                ('release_date', models.DateField()),
                ('VAT', models.BooleanField(default=False, verbose_name='ПДФ')),
                ('dimensions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Dimension')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='GeneralContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('contractor_full_name', models.CharField(max_length=64)),
                ('SBR_code', models.IntegerField(verbose_name='ЕГРПОУ')),
                ('number', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator('^[\\w]*$')])),
                ('VAT', models.BooleanField(default=False, verbose_name='ПДФ')),
                ('active_from', models.DateField()),
                ('chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='common.Chain')),
                ('cinema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='common.Cinema')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время начала')),
                ('viewers_count', models.PositiveSmallIntegerField(verbose_name='Зрители')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Мин цена')),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Макс цена')),
                ('week', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Неделя')),
                ('invitations_count', models.PositiveSmallIntegerField(default=0, verbose_name='Пригл.')),
                ('gross_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Доход')),
                ('VAT', models.BooleanField(default=False, verbose_name='ПДФ')),
                ('is_daily_report_finished', models.BooleanField(default=False)),
                ('cinema_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='common.CinemaHall', verbose_name='Зал')),
                ('dimensions', models.ManyToManyField(related_name='sessions', to='common.Dimension', verbose_name='Форматы')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Film', verbose_name='фильм')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
                'ordering': ('date',),
            },
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='dimensions',
            field=models.ManyToManyField(related_name='halls', to='common.Dimension'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.City', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='additionalagreement',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='common.Chain'),
        ),
        migrations.AddField(
            model_name='additionalagreement',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='common.GeneralContract'),
        ),
        migrations.AddField(
            model_name='additionalagreement',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Dimension'),
        ),
        migrations.AddField(
            model_name='additionalagreement',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='common.Film'),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set([('cinema_hall', 'time', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='cinemahall',
            unique_together=set([('name', 'cinema')]),
        ),
        migrations.AlterUniqueTogether(
            name='cinema',
            unique_together=set([('name', 'city', 'chain')]),
        ),
    ]
