# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20161228_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinemahall',
            options={'ordering': ('name',), 'verbose_name': 'Кинозал', 'verbose_name_plural': 'Залы'},
        ),
        migrations.AlterModelOptions(
            name='generalcontract',
            options={'ordering': ('created',), 'verbose_name': 'Контракт', 'verbose_name_plural': 'Генеральные Контракты'},
        ),
        migrations.AlterField(
            model_name='session',
            name='gross_yield',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Доход'),
        ),
    ]
