# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_remove_session_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='month',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='week',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
