# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20161231_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Сеанс', 'verbose_name_plural': 'Сеансы'},
        ),
    ]
