# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20170101_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='dimensions',
        ),
        migrations.AddField(
            model_name='film',
            name='dimensions',
            field=models.ManyToManyField(to='common.Dimension'),
        ),
    ]
