# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_auto_20170103_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='start_of_month',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='start_of_week',
            new_name='week',
        ),
    ]
