# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20170103_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='halls_count',
            field=models.PositiveSmallIntegerField(default=10),
            preserve_default=False,
        ),
    ]
