# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 15:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_auto_20170106_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='xls_row_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
