# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import kinomania.utils


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_session_xls_row_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xlssessionsreport',
            name='xls_file',
            field=models.FileField(upload_to='xls_reports', validators=[kinomania.utils.validate_xls_extension]),
        ),
    ]
