# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20170106_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='xls_row_data',
            new_name='xls_raw_data',
        ),
    ]
