# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_auto_20170106_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='name',
            field=models.CharField(max_length=3),
        ),
    ]
