# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import kinomania.utils


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_auto_20170110_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xlssessionsreport',
            name='xls_file',
            field=models.FileField(upload_to='xls_reports/%Y/%m/%d/', validators=[kinomania.utils.validate_xls_extension]),
        ),
    ]
