# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_auto_20170110_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='name',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
