# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_auto_20170110_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
