# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 10:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_auto_20170110_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalcontract',
            name='SBR_code',
            field=models.IntegerField(unique=True, verbose_name='ЕГРПОУ'),
        ),
        migrations.AlterField(
            model_name='generalcontract',
            name='number',
            field=models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[\\w]*$')]),
        ),
    ]
