# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0028_auto_20170111_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xlsreportsupload',
            name='is_successful',
            field=models.BooleanField(default=False),
        ),
    ]
