# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_auto_20170111_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='xlssessionsreport',
            name='xls_filename',
            field=models.CharField(default='defaultname', max_length=256),
            preserve_default=False,
        ),
    ]
