# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0032_auto_20170112_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xlsreportsupload',
            name='is_successful',
        ),
    ]
