# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0033_remove_xlsreportsupload_is_successful'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalcontract',
            options={'ordering': ('created',), 'verbose_name': 'Контракт', 'verbose_name_plural': 'Генеральные контракты'},
        ),
        migrations.AlterField(
            model_name='cinema',
            name='halls_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Залов'),
        ),
    ]
