# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 15:21
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.ranges
from django.db import migrations
from django.utils.timezone import utc, now
from psycopg2._range import DateRange


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0035_additionalagreement_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalagreement',
            name='active_date_range',
            field=django.contrib.postgres.fields.ranges.DateRangeField(default=DateRange(datetime.date(2017, 2, 15), datetime.date(2017, 4, 13))),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='additionalagreement',
            unique_together=set([('cinema', 'film', 'active_from', 'dimension', 'language')]),
        ),
    ]
