# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0036_auto_20170113_1721'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='additionalagreement',
            unique_together=set([('cinema', 'film', 'dimension', 'language', 'active_date_range')]),
        ),
    ]
