# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0037_auto_20170113_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalagreement',
            name='active_from',
        ),
        migrations.RemoveField(
            model_name='additionalagreement',
            name='active_to',
        ),
    ]
