# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0040_auto_20170117_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='gross_yield_without_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Доход с вычетом ПДВ'),
        ),
    ]
