# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0041_auto_20170117_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='week',
            field=models.DateField(blank=True, null=True),
        ),
    ]
