# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0042_auto_20170117_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finishedcinemareportdate',
            options={'verbose_name': 'Дата завершенного отчёта', 'verbose_name_plural': 'Даты завершенных отчётов'},
        ),
        migrations.AddField(
            model_name='film',
            name='name_original',
            field=models.CharField(blank=True, help_text='Оригинальное название', max_length=128),
        ),
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(help_text='На украинском языке', max_length=128),
        ),
    ]
