# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0043_auto_20170118_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='VAT',
        ),
        migrations.RemoveField(
            model_name='generalcontract',
            name='VAT',
        ),
        migrations.RemoveField(
            model_name='session',
            name='VAT',
        ),
        migrations.AddField(
            model_name='additionalagreement',
            name='vat',
            field=models.NullBooleanField(verbose_name='НДС'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='vat',
            field=models.BooleanField(default=False, verbose_name='НДС'),
        ),
        migrations.AddField(
            model_name='session',
            name='vat',
            field=models.BooleanField(default=False, verbose_name='НДС'),
        ),
        migrations.AlterField(
            model_name='session',
            name='gross_yield_without_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Доход с вычетом НДС'),
        ),
    ]
