# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0045_session_additional_agreement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='dimensions',
        ),
        migrations.AddField(
            model_name='session',
            name='dimension',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='common.Dimension', verbose_name='Формат'),
            preserve_default=False,
        ),
    ]
