# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0046_auto_20170119_1024'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set([('cinema_hall', 'time', 'date', 'dimension')]),
        ),
    ]
