# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0048_auto_20170119_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='chain_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='common.GeneralContract'),
        ),
    ]
