# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0049_cinema_chain_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='chain_contract',
            field=models.ForeignKey(blank=True, help_text='Выберите один из контактов сети или содайте ниже конктракт непосредственно для кинотеатра', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='common.GeneralContract'),
        ),
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(help_text='На украинском языке', max_length=128, unique=True),
        ),
    ]
