# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0050_auto_20170120_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='code',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
