# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 19:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0052_auto_20170127_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='access_to_reports',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_chain', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chain',
            name='responsible_for_daily_reports',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chain', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='access_to_reports',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_cinemas', to=settings.AUTH_USER_MODEL, verbose_name='Доступ к отчётам'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='chain_contract',
            field=models.ForeignKey(blank=True, help_text='Выберите один из контактов сети или содайте ниже конктракт непосредственно для кинотеатра', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='common.GeneralContract', verbose_name='Контракт сети'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='responsible_for_daily_reports',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cinemas', to=settings.AUTH_USER_MODEL, verbose_name='Дневные отчёты'),
        ),
        migrations.AlterField(
            model_name='session',
            name='additional_agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='common.AdditionalAgreement'),
        ),
        migrations.AlterField(
            model_name='session',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='xls_session_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='common.XlsSessionsReport'),
        ),
    ]
