# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0053_auto_20170128_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='name',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(db_index=True, help_text='На украинском языке', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Дата'),
        ),
    ]
