# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0056_auto_20170217_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_original_language',
            field=models.BooleanField(default=False, help_text='Указывает на то был ли показ фильма а языке оригиала'),
        ),
        migrations.AlterField(
            model_name='session',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='common.Film', verbose_name='фильм'),
        ),
        migrations.AlterUniqueTogether(
            name='additionalagreement',
            unique_together=set([('cinema', 'film', 'dimension', 'active_date_range')]),
        ),
    ]
