# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0057_auto_20170221_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalagreement',
            name='language',
        ),
    ]
