# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0058_remove_additionalagreement_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalagreement',
            name='is_original_language',
            field=models.BooleanField(default=False, help_text='Показ фильма а языке оригиала?', max_length=10),
        ),
    ]
