# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 15:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0060_auto_20170221_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalagreement',
            name='vat',
            field=models.NullBooleanField(help_text='Если НДС не указано, то будет взято значение из кинотеатра', verbose_name='НДС'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='generalcontract',
            name='number',
            field=models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[\\w-]*$')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='is_original_language',
            field=models.BooleanField(default=False, help_text='Указывает на то, был ли показ фильма на языке оригинала', verbose_name='Ориг. язык'),
        ),
    ]
