# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0062_auto_20170320_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalcontract',
            name='SBR_code',
            field=models.BigIntegerField(unique=True, verbose_name='ЕГРПОУ'),
        ),
    ]
