# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0065_auto_20170321_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
