# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 08:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0066_auto_20170321_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text', models.TextField()),
                ('receivers_emails', models.CharField(max_length=256)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='additionalagreement',
            options={'ordering': ('created',), 'verbose_name': 'Доп. соглашение', 'verbose_name_plural': 'Дополнительные соглашения'},
        ),
        migrations.AlterModelOptions(
            name='finishedcinemareportdate',
            options={'verbose_name': 'Дата завершения отчёта', 'verbose_name_plural': 'Даты завершения отчётов'},
        ),
        migrations.AlterField(
            model_name='additionalagreement',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='common.Dimension'),
        ),
        migrations.AlterField(
            model_name='additionalagreement',
            name='is_original_language',
            field=models.BooleanField(default=False, help_text='Показ фильма на языке оригинала?', max_length=10),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='chain_contract',
            field=models.ForeignKey(blank=True, help_text='Выберите один из контактов сети или создайте ниже контракт непосредственно для кинотеатра', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='common.GeneralContract', verbose_name='Контракт сети'),
        ),
        migrations.AlterField(
            model_name='session',
            name='viewers_count',
            field=models.PositiveSmallIntegerField(help_text='Кол-во зрителей купивших билеты', verbose_name='Зрители'),
        ),
    ]
