# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0069_auto_20170412_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalcontract',
            old_name='cinema',
            new_name='_cinema',
        ),
    ]
