# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0070_auto_20170413_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalcontract',
            name='_cinema',
        ),
        migrations.AlterField(
            model_name='session',
            name='is_daily_report_finished',
            field=models.BooleanField(default=False, verbose_name='Отчёт сдан'),
        ),
    ]
