# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0071_auto_20170424_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='dimensions',
            field=models.ManyToManyField(related_name='films', to='common.Dimension'),
        ),
    ]
