# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0075_auto_20170616_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmedmonthlyreport',
            options={'verbose_name': 'Подтверждённый расчётный бланк', 'verbose_name_plural': 'Подтверждённые расчётные бланки'},
        ),
        migrations.AddField(
            model_name='additionalagreement',
            name='one_c_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='номер 1С'),
        ),
        migrations.AlterField(
            model_name='confirmedmonthlyreport',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_reports', to='common.Cinema', verbose_name='Кинотеатр'),
        ),
    ]
