# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-07 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0076_auto_20170706_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalagreement',
            name='one_c_number',
            field=models.CharField(max_length=64, unique=True, verbose_name='номер 1С'),
        ),
    ]
