# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-27 17:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0078_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='access_to_reports_test',
            field=models.ManyToManyField(related_name='report_cinemas_test', to=settings.AUTH_USER_MODEL, verbose_name='Доступ к отчётам'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='responsible_for_daily_reports_test',
            field=models.ManyToManyField(related_name='cinemas_test', to=settings.AUTH_USER_MODEL, verbose_name='Дневные отчёты'),
        ),
    ]
