# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-27 17:03
from __future__ import unicode_literals

from django.db import migrations


def forward(apps, schema_editor):
    Cinema = apps.get_model('common', 'Cinema')

    for cinema in Cinema.objects.all():
        if cinema.access_to_reports is not None:
            cinema.access_to_reports_test.add(cinema.access_to_reports)
        if cinema.responsible_for_daily_reports is not None:
            cinema.responsible_for_daily_reports_test.add(cinema.responsible_for_daily_reports)
        cinema.save()


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0079_auto_20180327_2001'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
