# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-27 18:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0080_auto_20180327_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='access_to_reports_test',
            field=models.ManyToManyField(blank=True, related_name='report_cinemas_test', to=settings.AUTH_USER_MODEL, verbose_name='Доступ к отчётам'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='responsible_for_daily_reports_test',
            field=models.ManyToManyField(blank=True, related_name='cinemas_test', to=settings.AUTH_USER_MODEL, verbose_name='Дневные отчёты'),
        ),
    ]
