# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-27 18:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0081_auto_20180327_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='access_to_reports',
        ),
        migrations.AddField(
            model_name='cinema',
            name='access_to_reports',
            field=models.ManyToManyField(blank=True, related_name='report_cinemas_test', to=settings.AUTH_USER_MODEL, verbose_name='Доступ к отчётам'),
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='access_to_reports_test',
        ),
        migrations.AddField(
            model_name='cinema',
            name='access_to_reports_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_cinemas', to=settings.AUTH_USER_MODEL, verbose_name='Доступ к отчётам'),
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='responsible_for_daily_reports',
        ),
        migrations.AddField(
            model_name='cinema',
            name='responsible_for_daily_reports',
            field=models.ManyToManyField(blank=True, related_name='cinemas_test', to=settings.AUTH_USER_MODEL, verbose_name='Дневные отчёты'),
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='responsible_for_daily_reports_test',
        ),
        migrations.AddField(
            model_name='cinema',
            name='responsible_for_daily_reports_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cinemas', to=settings.AUTH_USER_MODEL, verbose_name='Дневные отчёты'),
        ),
    ]
