# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-29 14:19
from __future__ import unicode_literals

from django.db import migrations


def forward(apps, schema_editor):
    TimeModel = apps.get_model('common', 'TimeBackup')
    TimeModel.objects.create(hour=0, minute=0)


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0087_timebackup'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
