# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-03 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0088_auto_20180629_1719'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeBackup',
        ),
    ]
