# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-03 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0089_delete_timebackup'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
            ],
        ),
    ]
